name: My First CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        run: |
          sudo apt update
          sudo apt install -y python3

      - name: Run app
        run: python3 app.py
